version: '3'
services:
  api:
    env_file:
      - .env
    build: .
    tty: true
    volumes:
      - .:/go/src/github.com/Cherry0202/RamenWikiStoreFunction
    # 環境変数確認
    command:
      - 'env'
    ports:
      - "8080:8080"

# TODO: create mysql
  mysql:
    image: mysql:5.7
    container_name: ramen_wiki_db_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3308:3306"